name: freedom_rent_car_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  google_fonts: ^4.0.5
  carousel_slider: ^5.0.0
  shared_preferences: ^2.2.1
  image_picker: ^1.1.2
  permission_handler: ^11.3.1
  flutter_bloc: ^8.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
  - assets/
